services:
  - type: web
    name: water-monitoring-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && gunicorn -w 4 -b 0.0.0.0:$PORT "api:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_NAME
        value: water_monitoring
      - key: LOG_LEVEL
        value: INFO
      - key: MONGO_URI
        scope: secret
